#pragma once
#include "enemies.h"
static const char LevelSequence1[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 3, 4, 0, 5, 6, 0, 1, 2, 
};

static const char LevelWaves1[] = {
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
};
