#pragma once
#include "enemies.h"
static const char LevelSequence0[] = {
	1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 0, 
	0, 0, 
};

static const char LevelWaves0[] = {
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_UFO_4, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_NONE, WAVE_CORVETTE_2, WAVE_CORVETTE_2, WAVE_CORVETTE_2, WAVE_CORVETTE_2, WAVE_NONE, 
	WAVE_NONE, WAVE_NONE, 
};
